#!/bin/bash
ARGUMENTS=$1

if [ "$ARGUMENTS" == "" ] || \
   [ "$ARGUMENTS" == "node" ];
   then
    exec $NODE_PREFIX/bin/node
    exit $?
fi

if [ "$ARGUMENTS" == "start" ]; then
    cd /app
    exec $NODE_PREFIX/bin/npm start
    exit $?
fi

if [ "$ARGUMENTS" == "shell" ] || \
   [ "$ARGUMENTS" == "sh" ] || \
   [ "$ARGUMENTS" == "bash" ] || \
   [ "$ARGUMENTS" == "/bin/bash" ] || \
   [ "$ARGUMENTS" == "/bin/sh" ];
   then
    exec /bin/sh -s
    exit $?
fi

echo "feature not implemented, please change entrypoint"
